server:
  port: 8080

statserver:
  url: http://statistics:9090

logging:
  level:
    org:
      my: INFO
      zalando.logbook: TRACE
  pattern:
    file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"