--TODO удалить DROP
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL UNIQUE,
  name varchar NOT NULL
);

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR NOT NULL,
  annotation VARCHAR(200) NOT NULL,
  description VARCHAR(7000) NOT NULL,
  category_id BIGINT NOT NULL,
  event_date TIMESTAMP NOT NULL,
  latitude NUMERIC(9,6),
  longitude NUMERIC(9,6),
  paid BOOL,
  participant_limit BIGINT,
  request_moderation BOOL,
  initiator_id BIGINT NOT NULL,
  created_on TIMESTAMP NOT NULL,
  published_on TIMESTAMP,
  state VARCHAR NOT NULL,
  CONSTRAINT fk_events_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_events_initiator_id FOREIGN KEY (initiator_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(name);
CREATE INDEX IF NOT EXISTS idx_users_name ON users(email);

