services:

  db-stat:
    image: postgres:16.1
    container_name: postgres-statistics
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-statistic
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
#      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  statistics:
    build: statistics/service
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      db-stat:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stat:5432/ewm-statistic
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
#      - TZ=Europe/Moscow
    networks:
      - backend

  db-serv:
    image: postgres:16.1
    container_name: postgres-ewm-main
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=mcat
      - POSTGRES_PASSWORD=54321
#      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  service:
    build: ewm-service/
    image: ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      db-stat:
        condition: service_healthy
      statistics:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-serv:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=mcat
      - SPRING_DATASOURCE_PASSWORD=54321
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - STATSERVER_URL=http://statistics:9090
      - APP_NAME=ewm-main-service;
#      - TZ=Europe/Moscow
    networks:
      - backend

networks:
  backend: