services:

  stats-server:
    build: statistics/service
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-statistic
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - ewm-backend

  stats-db:
    image: postgres:16.1
    container_name: postgres-statistics
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-statistic
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - ewm-backend

  ewm-service:
    build: ewm-service/
    image: ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"
#    environment:
#      - stats-server.url=http://localhost:9090
#    http://stats-server:9090
    depends_on:
      - stats-server
    #      - stats-db
    #    environment:
    #      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-statistic
    #      - SPRING_DATASOURCE_USERNAME=dbuser
    #      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - ewm-backend

#  ewm-db:
#    image: postgres:16.1

networks:
  ewm-backend:
    driver: bridge
    name: ewm