DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application varchar NOT NULL,
  uri varchar NOT NULL,
  ip inet NOT NULL,
  time timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_requests_timestamp_uri ON requests(time,uri);